/* WORKERS ACTION TYPES */
export const ADD_WORKER_TASK = 'ADD_WORKER_TASK';
export const REMOVE_WORKER_TASK = 'REMOVE_WORKER_TASK';



/* TASKS ACTION TYPES */
export const ADD_TRANSFER_TASK = 'ADD_TRANSFER_TASK';
export const REMOVE_TRANSFER_TASK = 'REMOVE_TRANSFER_TASK';
export const UPDATE_TRANSFER_TASK = 'UPDATE_TRANSFER_TASK';
export const STOP_TRANSFER_TASK = 'STOP_TRANSFER_TASK';
export const RESUME_TRANSFER_TASK = 'RESUME_TRANSFER_TASK';


/* COMPLETED TASKS REDUCER */
export const ADD_COMPLETED_TASK = 'ADD_COMPLETED_TASK';
